# Generated by Django 5.0.dev20230120115851 on 2023-01-24 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='room_number',
            new_name='code',
        ),
    ]
